/*
 * ROOMY — 아이콘 목록
 * Phosphor Icons 중에서 집에 있을 만한 물건 아이콘에 한글 이름과 찾을 말을 붙였어요.
 * [아이콘 이름, 한글 이름, 더 찾을 말]. 여기 없는 아이콘도 영어 이름으로 찾을 수 있어요 (OTHER_ICONS).
 */
window.ROOMY_ICONS = [
  ["문구·책",[["pencil-simple","연필"],
  ["pen","볼펜","펜"],
  ["pen-nib","만년필","펜촉"],
  ["marker-circle","사인펜","마커"],
  ["highlighter","형광펜"],
  ["eraser","지우개"],
  ["scissors","가위"],
  ["ruler","자","줄자"],
  ["pencil-ruler","제도용품","필통"],
  ["paperclip","클립"],
  ["push-pin","압정","핀"],
  ["sticker","스티커","포스트잇"],
  ["note","메모지","포스트잇"],
  ["note-pencil","메모"],
  ["notepad","메모장"],
  ["notebook","공책","노트"],
  ["book","책"],
  ["book-open","펼친 책","독서"],
  ["books","책 여러 권","책장 전집"],
  ["book-bookmark","다이어리","수첩 플래너"],
  ["bookmark-simple","책갈피"],
  ["folder","폴더","파일철 서류철"],
  ["files","서류","종이 프린트"],
  ["file-text","문서"],
  ["clipboard-text","클립보드"],
  ["envelope-simple","봉투","편지"],
  ["stamp","도장"],
  ["tag","태그","라벨 가격표"],
  ["calendar-blank","달력"],
  ["calculator","계산기"],
  ["palette","팔레트","물감"],
  ["paint-brush","붓","브러시"],
  ["newspaper","신문","잡지"],
  ["scroll","두루마리","포스터"],
  ["certificate","상장","자격증 증명서"],
  ["identification-card","신분증","카드 학생증"],
  ["identification-badge","사원증","명찰"],
  ["graduation-cap","학사모","졸업"],
  ["magnifying-glass","돋보기"],
  ["frame-corners","액자","사진틀"]]],
  ["전자기기",[["device-mobile","휴대폰","핸드폰 스마트폰 폰 아이폰"],
  ["device-tablet","태블릿","아이패드 패드"],
  ["laptop","노트북","맥북 컴퓨터"],
  ["desktop","데스크톱","컴퓨터 본체"],
  ["monitor","모니터"],
  ["television-simple","TV","티비 텔레비전"],
  ["keyboard","키보드"],
  ["mouse-simple","마우스"],
  ["headphones","헤드폰","이어폰"],
  ["headset","헤드셋"],
  ["speaker-high","스피커"],
  ["microphone","마이크"],
  ["camera","카메라"],
  ["video-camera","캠코더","비디오"],
  ["webcam","웹캠"],
  ["printer","프린터"],
  ["plug","충전기","플러그 어댑터"],
  ["plugs","멀티탭","콘센트 전선"],
  ["plug-charging","충전 케이블","충전선"],
  ["usb","USB","유에스비 케이블"],
  ["battery-full","건전지","배터리"],
  ["battery-charging","보조배터리","배터리"],
  ["hard-drives","외장하드"],
  ["floppy-disk","메모리카드","SD카드 USB 저장"],
  ["sim-card","유심","심카드"],
  ["cpu","컴퓨터 부품","칩"],
  ["wifi-high","공유기","와이파이 인터넷"],
  ["bluetooth","블루투스"],
  ["radio","라디오"],
  ["alarm","알람시계","자명종"],
  ["flashlight","손전등","랜턴"],
  ["projector-screen","프로젝터","스크린"],
  ["drone","드론"],
  ["robot","로봇","로봇청소기"],
  ["lightning","전기","번개"],
  ["watch","손목시계","스마트워치 애플워치"]]],
  ["옷·신발",[["t-shirt","티셔츠","반팔 옷 상의"],
  ["shirt-folded","셔츠","갠 옷 와이셔츠"],
  ["hoodie","후드티","니트 스웨터 맨투맨"],
  ["pants","바지","청바지 하의"],
  ["dress","원피스","드레스 치마"],
  ["coat-hanger","옷걸이","코트 외투"],
  ["sock","양말"],
  ["belt","벨트","허리띠"],
  ["baseball-cap","모자","캡"],
  ["cowboy-hat","챙모자","중절모"],
  ["beanie","비니","털모자"],
  ["sneaker","운동화","신발"],
  ["sneaker-move","러닝화","신발"],
  ["boot","부츠","장화"],
  ["high-heel","구두","하이힐"],
  ["towel","수건","타월"]]],
  ["가방·소지품",[["backpack","백팩","가방 책가방"],
  ["handbag","핸드백","가방"],
  ["tote","에코백","토트백 가방"],
  ["shopping-bag","쇼핑백"],
  ["suitcase","여행가방","트렁크"],
  ["suitcase-rolling","캐리어","여행"],
  ["briefcase","서류가방","가방"],
  ["wallet","지갑"],
  ["cardholder","카드지갑","명함지갑"],
  ["credit-card","카드","신용카드 체크카드"],
  ["money","지폐","현금 돈"],
  ["coins","동전","돈"],
  ["piggy-bank","저금통"],
  ["key","열쇠","키"],
  ["lock","자물쇠"],
  ["eyeglasses","안경"],
  ["sunglasses","선글라스"],
  ["umbrella","우산","양산"],
  ["diamond","보석","반지 목걸이 액세서리"],
  ["ticket","티켓","표 입장권"],
  ["receipt","영수증"],
  ["hand-coins","용돈","돈"]]],
  ["화장품·욕실",[["drop","스킨","토너 화장품 물방울"],
  ["drop-half","로션","크림"],
  ["flower","향수","꽃"],
  ["sparkle","반짝이","글리터 하이라이터"],
  ["hand-soap","핸드워시","비누 펌프 바디워시"],
  ["spray-bottle","스프레이","미스트 분무기"],
  ["sun","선크림","썬크림 자외선"],
  ["eye","렌즈","아이섀도 눈"],
  ["hair-dryer","드라이어","헤어드라이어"],
  ["tooth","칫솔","치약 치아"],
  ["shower","샤워기","샴푸"],
  ["bathtub","욕조","입욕제"],
  ["toilet","변기"],
  ["toilet-paper","휴지","화장지 두루마리"],
  ["face-mask","마스크"],
  ["hand","핸드크림","손"]]],
  ["주방·음식",[["coffee","머그컵","커피 컵"],
  ["coffee-bean","원두","커피"],
  ["tea-bag","티백","차 녹차"],
  ["pint-glass","유리컵","컵"],
  ["wine","와인","와인잔"],
  ["beer-bottle","맥주","병"],
  ["beer-stein","맥주잔"],
  ["martini","칵테일"],
  ["champagne","샴페인"],
  ["brandy","양주"],
  ["jar","유리병","병 잼"],
  ["jar-label","소스","양념 병"],
  ["cooking-pot","냄비","솥"],
  ["fork-knife","수저","포크 나이프 식기"],
  ["knife","칼","식칼"],
  ["bowl-food","그릇","밥그릇 국그릇"],
  ["bowl-steam","국그릇","라면 수프"],
  ["oven","오븐","전자레인지 에어프라이어"],
  ["chef-hat","앞치마","요리 요리사"],
  ["egg","달걀","계란"],
  ["bread","빵"],
  ["cake","케이크"],
  ["cookie","과자","쿠키"],
  ["pizza","피자"],
  ["hamburger","햄버거"],
  ["carrot","채소","당근"],
  ["cherries","과일","체리"],
  ["orange","오렌지","귤 과일"],
  ["orange-slice","레몬","과일"],
  ["avocado","아보카도"],
  ["pepper","고추","후추"],
  ["popcorn","팝콘","간식"],
  ["popsicle","아이스크림","하드"],
  ["ice-cream","콘 아이스크림"],
  ["cheese","치즈"],
  ["grains","곡식","쌀 잡곡"],
  ["fish-simple","생선","물고기"],
  ["shrimp","새우"]]],
  ["가구·집",[["house","집"],
  ["door","문"],
  ["couch","소파"],
  ["armchair","안락의자","의자"],
  ["chair","의자"],
  ["office-chair","사무용 의자","의자"],
  ["desk","책상"],
  ["dresser","서랍장","옷장 수납장"],
  ["bed","침대","이불 베개"],
  ["lamp","스탠드","조명 램프"],
  ["lamp-pendant","천장 조명","조명"],
  ["lightbulb","전구"],
  ["fan","선풍기"],
  ["fire","난로","히터"],
  ["flame","양초","캔들 초"],
  ["snowflake","에어컨","겨울 눈"],
  ["wind","공기청정기","바람"],
  ["thermometer","온도계"],
  ["clock","벽시계","시계"],
  ["image","사진","액자 그림"],
  ["warehouse","창고"],
  ["lockers","사물함","락커"],
  ["vault","금고"]]],
  ["정리·청소·세탁",[["package","상자","택배 박스"],
  ["archive-box","수납함","보관함"],
  ["archive","수납 서랍","서랍"],
  ["tray","정리함","트레이"],
  ["cube","큐브","블록 상자"],
  ["basket","바구니","빨래바구니"],
  ["shopping-cart","장바구니","카트"],
  ["broom","빗자루","청소"],
  ["washing-machine","세탁기","빨래"],
  ["trash","쓰레기통"],
  ["recycle","분리수거","재활용"],
  ["paint-bucket","양동이","페인트통"]]],
  ["약·건강",[["first-aid-kit","구급상자"],
  ["first-aid","응급","구급"],
  ["pill","약","알약 영양제"],
  ["bandaids","밴드","반창고"],
  ["syringe","주사기"],
  ["thermometer-simple","체온계"],
  ["heartbeat","혈압계","건강"],
  ["stethoscope","청진기","병원"],
  ["eyedropper","안약","스포이트"],
  ["wheelchair","휠체어"],
  ["barbell","아령","덤벨 운동 헬스"]]],
  ["공구·수리",[["wrench","스패너","렌치 공구"],
  ["hammer","망치"],
  ["screwdriver","드라이버"],
  ["toolbox","공구함","공구"],
  ["nut","너트","볼트 나사"],
  ["gear","부품","톱니"],
  ["ladder","사다리"],
  ["magnet","자석"],
  ["hard-hat","안전모","헬멧"],
  ["axe","도끼"],
  ["shovel","삽","모종삽"],
  ["paint-roller","롤러","페인트"],
  ["needle","바늘","반짇고리 바느질"],
  ["yarn","털실","뜨개질"]]],
  ["취미·운동",[["basketball","농구공"],
  ["soccer-ball","축구공"],
  ["baseball","야구공"],
  ["tennis-ball","테니스공"],
  ["volleyball","배구공"],
  ["football","럭비공"],
  ["golf","골프"],
  ["ping-pong","탁구","라켓"],
  ["bowling-ball","볼링공"],
  ["boxing-glove","권투장갑","글러브"],
  ["bicycle","자전거"],
  ["tent","텐트","캠핑"],
  ["campfire","캠핑","모닥불"],
  ["mountains","등산"],
  ["swimming-pool","수영","수영복"],
  ["binoculars","쌍안경"],
  ["target","다트","과녁"],
  ["puzzle-piece","퍼즐"],
  ["dice-five","주사위","보드게임"],
  ["cards","카드게임","트럼프 화투"],
  ["horse","체스","장기"]]],
  ["음악·영상·게임",[["guitar","기타","악기 우쿨렐레"],
  ["piano-keys","피아노","건반 키보드"],
  ["music-notes","음악","음표 악보"],
  ["microphone-stage","노래 마이크","노래방"],
  ["metronome","메트로놈"],
  ["vinyl-record","LP","레코드판"],
  ["cassette-tape","카세트","테이프"],
  ["disc","CD","DVD 음반"],
  ["film-slate","영화"],
  ["film-strip","필름"],
  ["game-controller","게임패드","닌텐도 플스 게임기"],
  ["joystick","조이스틱","게임"]]],
  ["여행·탈것",[["airplane","비행기","여행"],
  ["car","자동차","차"],
  ["motorcycle","오토바이"],
  ["scooter","킥보드","스쿠터"],
  ["boat","배"],
  ["rocket","로켓"],
  ["map-trifold","지도"],
  ["compass","나침반"],
  ["globe","지구본","여행 세계"]]],
  ["식물·동물",[["plant","화분","식물"],
  ["potted-plant","큰 화분","식물 화분"],
  ["cactus","선인장"],
  ["flower-tulip","튤립","꽃"],
  ["flower-lotus","연꽃","꽃"],
  ["leaf","잎","나뭇잎"],
  ["tree","나무"],
  ["tree-evergreen","트리","크리스마스"],
  ["dog","강아지","개 반려동물"],
  ["cat","고양이","반려동물"],
  ["bird","새"],
  ["fish","물고기","어항"],
  ["paw-print","반려동물 용품","발바닥"],
  ["bone","개껌","뼈다귀"],
  ["rabbit","토끼"],
  ["butterfly","나비"],
  ["bug","벌레","곤충"]]],
  ["기념·기타",[["gift","선물"],
  ["star","별"],
  ["heart","하트","사랑"],
  ["smiley","스마일","웃음"],
  ["balloon","풍선"],
  ["confetti","파티","축하"],
  ["crown","왕관"],
  ["trophy","트로피","상"],
  ["medal","메달"],
  ["flag","깃발"],
  ["magic-wand","요술봉"],
  ["ghost","유령"],
  ["skull","해골"],
  ["baby","아기","아기용품"],
  ["baby-carriage","유모차"],
  ["moon","달"],
  ["rainbow","무지개"],
  ["cloud","구름"],
  ["question","물음표","모르는 것"]]]];

window.ROOMY_OTHER_ICONS = "acorn activity address-book address-book-tabs air-traffic-control airplane-in-flight airplane-landing airplane-takeoff airplane-taxiing airplane-tilt airplay alien align-bottom align-bottom-simple align-center-horizontal align-center-horizontal-simple align-center-vertical align-center-vertical-simple align-left align-left-simple align-right align-right-simple align-top align-top-simple amazon-logo ambulance anchor anchor-simple android-logo angle angular-logo aperture app-store-logo app-window apple-logo apple-podcasts-logo approximate-equals archive-tray arrow-arc-left arrow-arc-right arrow-bend-double-up-left arrow-bend-double-up-right arrow-bend-down-left arrow-bend-down-right arrow-bend-left-down arrow-bend-left-up arrow-bend-right-down arrow-bend-right-up arrow-bend-up-left arrow-bend-up-right arrow-circle-down arrow-circle-down-left arrow-circle-down-right arrow-circle-left arrow-circle-right arrow-circle-up arrow-circle-up-left arrow-circle-up-right arrow-clockwise arrow-counter-clockwise arrow-down arrow-down-left arrow-down-right arrow-elbow-down-left arrow-elbow-down-right arrow-elbow-left arrow-elbow-left-down arrow-elbow-left-up arrow-elbow-right arrow-elbow-right-down arrow-elbow-right-up arrow-elbow-up-left arrow-elbow-up-right arrow-fat-down arrow-fat-left arrow-fat-line-down arrow-fat-line-left arrow-fat-line-right arrow-fat-line-up arrow-fat-lines-down arrow-fat-lines-left arrow-fat-lines-right arrow-fat-lines-up arrow-fat-right arrow-fat-up arrow-left arrow-line-down arrow-line-down-left arrow-line-down-right arrow-line-left arrow-line-right arrow-line-up arrow-line-up-left arrow-line-up-right arrow-right arrow-square-down arrow-square-down-left arrow-square-down-right arrow-square-in arrow-square-left arrow-square-out arrow-square-right arrow-square-up arrow-square-up-left arrow-square-up-right arrow-u-down-left arrow-u-down-right arrow-u-left-down arrow-u-left-up arrow-u-right-down arrow-u-right-up arrow-u-up-left arrow-u-up-right arrow-up arrow-up-left arrow-up-right arrows-clockwise arrows-counter-clockwise arrows-down-up arrows-horizontal arrows-in arrows-in-cardinal arrows-in-line-horizontal arrows-in-line-vertical arrows-in-simple arrows-left-right arrows-merge arrows-out arrows-out-cardinal arrows-out-line-horizontal arrows-out-line-vertical arrows-out-simple arrows-split arrows-vertical article article-medium article-ny-times asclepius asterisk asterisk-simple at atom backspace bag bag-simple bank barcode barn barricade baseball-helmet battery-charging-vertical battery-empty battery-high battery-low battery-medium battery-plus battery-plus-vertical battery-vertical-empty battery-vertical-full battery-vertical-high battery-vertical-low battery-vertical-medium battery-warning battery-warning-vertical beach-ball behance-logo bell bell-ringing bell-simple bell-simple-ringing bell-simple-slash bell-simple-z bell-slash bell-z bezier-curve binary biohazard blueprint bluetooth-connected bluetooth-slash bluetooth-x bomb book-open-text book-open-user bookmark bookmarks bookmarks-simple boules bounding-box box-arrow-down box-arrow-up brackets-angle brackets-curly brackets-round brackets-square brain bridge briefcase-metal broadcast browser browsers bug-beetle bug-droid building building-apartment building-office buildings bulldozer bus cable-car caduceus calendar calendar-check calendar-dot calendar-dots calendar-heart calendar-minus calendar-plus calendar-slash calendar-star calendar-x call-bell camera-plus camera-rotate camera-slash car-battery car-profile car-simple cards-three caret-circle-double-down caret-circle-double-left caret-circle-double-right caret-circle-double-up caret-circle-down caret-circle-left caret-circle-right caret-circle-up caret-circle-up-down caret-double-down caret-double-left caret-double-right caret-double-up caret-down caret-left caret-line-down caret-line-left caret-line-right caret-line-up caret-right caret-up caret-up-down cash-register castle-turret cell-signal-full cell-signal-high cell-signal-low cell-signal-medium cell-signal-none cell-signal-slash cell-signal-x cell-tower chalkboard chalkboard-simple chalkboard-teacher charging-station chart-bar chart-bar-horizontal chart-donut chart-line chart-line-down chart-line-up chart-pie chart-pie-slice chart-polar chart-scatter chat chat-centered chat-centered-dots chat-centered-slash chat-centered-text chat-circle chat-circle-dots chat-circle-slash chat-circle-text chat-dots chat-slash chat-teardrop chat-teardrop-dots chat-teardrop-slash chat-teardrop-text chat-text chats chats-circle chats-teardrop check check-circle check-fat check-square check-square-offset checkerboard checks cheers church cigarette cigarette-slash circle circle-dashed circle-half circle-half-tilt circle-notch circle-wavy circle-wavy-check circle-wavy-question circle-wavy-warning circles-four circles-three circles-three-plus circuitry city clipboard clock-afternoon clock-clockwise clock-countdown clock-counter-clockwise clock-user closed-captioning cloud-arrow-down cloud-arrow-up cloud-check cloud-fog cloud-lightning cloud-moon cloud-rain cloud-slash cloud-snow cloud-sun cloud-warning cloud-x clover club coda-logo code code-block code-simple codepen-logo codesandbox-logo coin coin-vertical columns columns-plus-left columns-plus-right command compass-rose compass-tool computer-tower contactless-payment control copy copy-simple copyleft copyright corners-in corners-out court-basketball cow crane crane-tower cricket crop cross crosshair crosshair-simple crown-cross crown-simple cube-focus cube-transparent currency-btc currency-circle-dollar currency-cny currency-dollar currency-dollar-simple currency-eth currency-eur currency-gbp currency-inr currency-jpy currency-krw currency-kzt currency-ngn currency-rub cursor cursor-click cursor-text cylinder database desktop-tower detective dev-to-logo device-mobile-camera device-mobile-slash device-mobile-speaker device-rotate device-tablet-camera device-tablet-speaker devices diamonds-four dice-four dice-one dice-six dice-three dice-two disco-ball discord-logo divide dna door-open dot dot-outline dots-nine dots-six dots-six-vertical dots-three dots-three-circle dots-three-circle-vertical dots-three-outline dots-three-outline-vertical dots-three-vertical download download-simple dribbble-logo drop-half-bottom drop-simple drop-slash dropbox-logo ear ear-slash egg-crack eject eject-simple elevator empty engine envelope envelope-open envelope-simple-open equalizer equals escalator-down escalator-up exam exclamation-mark exclude exclude-square export eye-closed eye-slash eyedropper-sample eyes facebook-logo factory faders faders-horizontal fallout-shelter farm fast-forward fast-forward-circle feather fediverse-logo figma-logo file file-archive file-arrow-down file-arrow-up file-audio file-c file-c-sharp file-cloud file-code file-cpp file-css file-csv file-dashed file-doc file-dotted file-html file-image file-ini file-jpg file-js file-jsx file-lock file-magnifying-glass file-md file-minus file-pdf file-plus file-png file-ppt file-py file-rs file-search file-sql file-svg file-ts file-tsx file-txt file-video file-vue file-x file-xls file-zip film-reel film-script fingerprint fingerprint-simple finn-the-human fire-extinguisher fire-simple fire-truck flag-banner flag-banner-fold flag-checkered flag-pennant flask flip-horizontal flip-vertical floppy-disk-back flow-arrow flying-saucer folder-dashed folder-dotted folder-lock folder-minus folder-notch folder-notch-minus folder-notch-open folder-notch-plus folder-open folder-plus folder-simple folder-simple-dashed folder-simple-dotted folder-simple-lock folder-simple-minus folder-simple-plus folder-simple-star folder-simple-user folder-star folder-user folders football-helmet footprints four-k framer-logo function funnel funnel-simple funnel-simple-x funnel-x garage gas-can gas-pump gauge gavel gear-fine gear-six gender-female gender-intersex gender-male gender-neuter gender-nonbinary gender-transgender gif git-branch git-commit git-diff git-fork git-merge git-pull-request github-logo gitlab-logo gitlab-logo-simple globe-hemisphere-east globe-hemisphere-west globe-simple globe-simple-x globe-stand globe-x goggles goodreads-logo google-cardboard-logo google-chrome-logo google-drive-logo google-logo google-photos-logo google-play-logo google-podcasts-logo gps gps-fix gps-slash gradient grains-slash graph graphics-card greater-than greater-than-or-equal grid-four grid-nine hand-arrow-down hand-arrow-up hand-deposit hand-eye hand-fist hand-grabbing hand-heart hand-palm hand-peace hand-pointing hand-swipe-left hand-swipe-right hand-tap hand-waving hand-withdraw handbag-simple hands-clapping hands-praying handshake hard-drive hash hash-straight head-circuit headlights heart-break heart-half heart-straight heart-straight-break hexagon high-definition highlighter-circle hockey hospital hourglass hourglass-high hourglass-low hourglass-medium hourglass-simple hourglass-simple-high hourglass-simple-low hourglass-simple-medium house-line house-simple hurricane image-broken image-square images images-square infinity info instagram-logo intersect intersect-square intersect-three intersection invoice island jeep kanban key-return keyhole ladder-simple lasso lastfm-logo layout lectern lego lego-smiley lemniscate less-than less-than-or-equal letter-circle-h letter-circle-p letter-circle-v lifebuoy lightbulb-filament lighthouse lightning-a lightning-slash line-segment line-segments line-vertical link link-break link-simple link-simple-break link-simple-horizontal link-simple-horizontal-break linkedin-logo linktree-logo linux-logo list list-bullets list-checks list-dashes list-heart list-magnifying-glass list-numbers list-plus list-star lock-key lock-key-open lock-laminated lock-laminated-open lock-open lock-simple lock-simple-open log magnet-straight magnifying-glass-minus magnifying-glass-plus mailbox map-pin map-pin-area map-pin-line map-pin-plus map-pin-simple map-pin-simple-area map-pin-simple-line markdown-logo mask-happy mask-sad mastodon-logo math-operations matrix-logo medal-military medium-logo megaphone megaphone-simple member-of memory messenger-logo meta-logo meteor microphone-slash microscope microsoft-excel-logo microsoft-outlook-logo microsoft-powerpoint-logo microsoft-teams-logo microsoft-word-logo minus minus-circle minus-square money-wavy monitor-arrow-up monitor-play moon-stars moped moped-front mosque mouse mouse-left-click mouse-middle-click mouse-right-click mouse-scroll music-note music-note-simple music-notes-minus music-notes-plus music-notes-simple navigation-arrow network network-slash network-x newspaper-clipping not-equals not-member-of not-subset-of not-superset-of notches note-blank notification notion-logo nuclear-plant number-circle-eight number-circle-five number-circle-four number-circle-nine number-circle-one number-circle-seven number-circle-six number-circle-three number-circle-two number-circle-zero number-eight number-five number-four number-nine number-one number-seven number-six number-square-eight number-square-five number-square-four number-square-nine number-square-one number-square-seven number-square-six number-square-three number-square-two number-square-zero number-three number-two number-zero numpad ny-times-logo octagon onigiri open-ai-logo option paint-brush-broad paint-brush-household panorama paper-plane paper-plane-right paper-plane-tilt paperclip-horizontal parachute paragraph parallelogram park password path patreon-logo pause pause-circle paypal-logo peace pen-nib-straight pencil pencil-circle pencil-line pencil-simple-line pencil-simple-slash pencil-slash pentagon pentagram percent person person-arms-spread person-simple person-simple-bike person-simple-circle person-simple-hike person-simple-run person-simple-ski person-simple-snowboard person-simple-swim person-simple-tai-chi person-simple-throw person-simple-walk perspective phone phone-call phone-disconnect phone-incoming phone-list phone-outgoing phone-pause phone-plus phone-slash phone-transfer phone-x phosphor-logo pi picnic-table picture-in-picture pinterest-logo pinwheel pipe pipe-wrench pix-logo placeholder planet play play-circle play-pause playlist plugs-connected plus plus-circle plus-minus plus-square poker-chip police-car polygon power prescription presentation presentation-chart prohibit prohibit-inset projector-screen-chart pulse push-pin-simple push-pin-simple-slash push-pin-slash qr-code question-mark queue quotes racquet radical radio-button radioactive rainbow-cloud ranking read-cv-logo receipt-x record rectangle rectangle-dashed reddit-logo repeat repeat-once replit-logo resize rewind rewind-circle road-horizon rocket-launch rows rows-plus-bottom rows-plus-top rss rss-simple rug sailboat scales scan scan-smiley screencast scribble scribble-loop seal seal-check seal-percent seal-question seal-warning seat seatbelt security-camera selection selection-all selection-background selection-foreground selection-inverse selection-plus selection-slash shapes share share-fat share-network shield shield-check shield-checkered shield-chevron shield-plus shield-slash shield-star shield-warning shipping-container shooting-star shopping-bag-open shopping-cart-simple shuffle shuffle-angular shuffle-simple sidebar sidebar-simple sigma sign-in sign-out signature signpost siren sketch-logo skip-back skip-back-circle skip-forward skip-forward-circle skype-logo slack-logo sliders sliders-horizontal slideshow smiley-angry smiley-blank smiley-meh smiley-melting smiley-nervous smiley-sad smiley-sticker smiley-wink smiley-x-eyes snapchat-logo solar-panel solar-roof sort-ascending sort-descending soundcloud-logo spade speaker-hifi speaker-low speaker-none speaker-simple-high speaker-simple-low speaker-simple-none speaker-simple-slash speaker-simple-x speaker-slash speaker-x speedometer sphere spinner spinner-ball spinner-gap spiral split-horizontal split-vertical spotify-logo square square-half square-half-bottom square-logo square-split-horizontal square-split-vertical squares-four stack stack-minus stack-overflow-logo stack-plus stack-simple stairs standard-definition star-and-crescent star-four star-half star-of-david steam-logo steering-wheel steps stool stop stop-circle storefront strategy stripe-logo student subset-of subset-proper-of subtitles subtitles-slash subtract subtract-square subway suitcase-simple sun-dim sun-horizon superset-of superset-proper-of swap swatches sword synagogue table tabs tag-chevron tag-simple taxi telegram-logo television terminal terminal-window test-tube text-a-underline text-aa text-align-center text-align-justify text-align-left text-align-right text-b text-bolder text-columns text-h text-h-five text-h-four text-h-one text-h-six text-h-three text-h-two text-indent text-italic text-outdent text-strikethrough text-subscript text-superscript text-t text-t-slash text-underline textbox thermometer-cold thermometer-hot threads-logo three-d thumbs-down thumbs-up tidal-logo tiktok-logo tilde timer tip-jar tipi tire toggle-left toggle-right tornado tote-simple tractor trademark trademark-registered traffic-cone traffic-sign traffic-signal train train-regional train-simple tram translate trash-simple tray-arrow-down tray-arrow-up treasure-chest tree-palm tree-structure tree-view trend-down trend-up triangle triangle-dashed trolley trolley-suitcase truck truck-trailer tumblr-logo twitch-logo twitter-logo umbrella-simple union unite unite-square upload upload-simple user user-check user-circle user-circle-check user-circle-dashed user-circle-gear user-circle-minus user-circle-plus user-focus user-gear user-list user-minus user-plus user-rectangle user-sound user-square user-switch users users-four users-three van vector-three vector-two vibrate video video-camera-slash video-conference vignette virtual-reality virus visor voicemail wall warning warning-circle warning-diamond warning-octagon wave-sawtooth wave-sine wave-square wave-triangle waveform waveform-slash waves webcam-slash webhooks-logo wechat-logo whatsapp-logo wheelchair-motion wifi-low wifi-medium wifi-none wifi-slash wifi-x windmill windows-logo x x-circle x-logo x-square yin-yang youtube-logo";
